---
- name: Configure Crucible
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Copy the pull secret and rename it
      copy:
        src: /home/redhat/pull-secret
        dest: /home/redhat/crucible/pull-secret.txt

    - name: Install Ansible requirements
      shell:
        cmd: ansible-galaxy collection install -r /home/redhat/crucible/requirements.yml