name: Crucible tests

on: [push, pull_request]

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install required dependencies
        run: |
          pip install ansible
          pip install -r requirements.txt

      - name: Run all tests using Ansible
        run: ansible-playbook tests/run_tests.yml
